services:

    ezautotranslate.ezadminui.component.javascripts:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         public: false
         arguments:
             $template: '@@EzPlatformAutomatedTranslation/ezadminui/javascripts.html.twig'
         tags:
             - { name: ezplatform.admin_ui.component, group: 'script-body' }

