services:

    ezautotranslate.ezadminui.component.javascripts:
         parent: Ibexa\AdminUi\Component\TwigComponent
         public: false
         arguments:
             $template: '@@EzPlatformAutomatedTranslation/ezadminui/javascripts.html.twig'
         tags:
             - { name: ibexa.admin_ui.component, group: 'script-body' }

