parameters:

services:
    _defaults:
        autowire: true
        public: false

    EzSystems\EzPlatformAutomatedTranslation\:
        resource: '../../../lib'

    EzSystems\EzPlatformAutomatedTranslation\Client\:
        resource: '../../../lib/Client'
        tags: ['ezplatform.automated_translation.client']

    EzSystems\EzPlatformAutomatedTranslation\ClientProvider:
        arguments: [!tagged ezplatform.automated_translation.client]

    EzSystems\EzPlatformAutomatedTranslationBundle\Command\:
        resource: '../../Command/*'
        tags: ["console.command"]

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Extension\TranslationAddType:
        tags:
            - { name: form.type_extension, extended_type: EzSystems\EzPlatformAdminUi\Form\Type\Content\Translation\TranslationAddType }

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Extension\ContentEditType:
        tags:
            - { name: form.type_extension, extended_type: EzSystems\RepositoryForms\Form\Type\Content\ContentEditType }


