services:
#    EzSystems\EzPlatformAutomatedTranslationBundle\Controller\TranslationController:
#        decorates: EzSystems\EzPlatformAdminUiBundle\Controller\TranslationController
#        autoconfigure: true
#        autowire: true
#        tags: ['controller.service_arguments']
##        lazy : true  # Segmentation fault (core dumped)

  EzSystems\EzPlatformAutomatedTranslationBundle\Controller\TranslationController:
    parent: EzSystems\EzPlatformAdminUiBundle\Controller\TranslationController
    arguments:
      $translationHelper: '@ezpublish.translation_helper'
