services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAutomatedTranslationBundle\:
        resource: '../../../bundle/*'
        exclude:
            - '../../../bundle/DependencyInjection/'
            - '../../../bundle/Entity/'
            - '../../../bundle/IbexaAutomatedTranslationBundle.php'

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Type\SubtreeLocationType:
        tags:
            - { name: form.type, alias: field.subtree_location }

    _instanceof:
        EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\FieldEncoderInterface:
            tags: [ 'ezplatform.automated_translation.field_encoder' ]

        EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\BlockAttributeEncoderInterface:
            tags: [ 'ezplatform.automated_translation.block_attribute_encoder' ]

        EzSystems\EzPlatformAutomatedTranslation\Encoder\FormBuilderFieldAttribute\FormBuilderFieldAttributeEncoderInterface:
            tags: [ 'ezplatform.automated_translation.form_builder_field_encoder' ]

        Symfony\Component\Console\Command\Command:
            tags:
                - { name: console.command }
                - { name: monolog.logger, channel: translate_content_cmd }

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\FormBuilderFieldEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\ImageFieldEncoder: ~
    # field encoder
    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\TextLineFieldEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\TextBlockFieldEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\UrlFieldEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\MetasFieldEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\PageBuilderFieldEncoder:
        arguments:
            $blockAttributeEncoderManager: '@EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\BlockAttributeEncoderManager'
            $blockDefinitionFactory: '@Ibexa\FieldTypePage\FieldType\Page\Block\Definition\BlockDefinitionFactory'

    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\RichTextFieldEncoder:
        arguments:
            $richTextEncoder: '@EzSystems\EzPlatformAutomatedTranslation\Encoder\RichText\RichTextEncoder'

    # field encoder manager
    EzSystems\EzPlatformAutomatedTranslation\Encoder\Field\FieldEncoderManager:
        arguments:
            $fieldEncoders: !tagged_iterator 'ezplatform.automated_translation.field_encoder'

    # block attribute
    EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\TextBlockAttributeEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\TextLineAttributeEncoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\RichTextBlockAttributeEncoder:
        arguments:
            $richTextEncoder: '@EzSystems\EzPlatformAutomatedTranslation\Encoder\RichText\RichTextEncoder'

    # block attribute encoder manager
    EzSystems\EzPlatformAutomatedTranslation\Encoder\BlockAttribute\BlockAttributeEncoderManager:
        arguments:
            $blockAttributeEncoders: !tagged_iterator 'ezplatform.automated_translation.block_attribute_encoder'

    # RichText encoder
    EzSystems\EzPlatformAutomatedTranslation\Encoder\RichText\RichTextEncoder:
        arguments:
            $configResolver: '@ibexa.config.resolver'

    # Form Builder Field attribute
    EzSystems\EzPlatformAutomatedTranslation\Encoder\FormBuilderFieldAttribute\TextLineFieldEncoder: ~
    EzSystems\EzPlatformAutomatedTranslation\Encoder\FormBuilderFieldAttribute\TextBlockFieldEncoder: ~
    # Form Builder Field attribute encoder manager
    EzSystems\EzPlatformAutomatedTranslation\Encoder\FormBuilderFieldAttribute\FormBuilderFieldAttributeEncoderManager:
        arguments:
            $formBuilderFieldAttributeEncoders: !tagged_iterator 'ezplatform.automated_translation.form_builder_field_encoder'

    EzSystems\EzPlatformAutomatedTranslation\Encoder: ~

    EzSystems\EzPlatformAutomatedTranslation\Translator: ~

    EzSystems\EzPlatformAutomatedTranslation\TranslatorGuard: ~

    EzSystems\EzPlatformAutomatedTranslation\Client\:
        resource: '../../../lib/Client'
        tags: ['ezplatform.automated_translation.client']

    EzSystems\EzPlatformAutomatedTranslation\ClientProvider:
        arguments: [!tagged ezplatform.automated_translation.client]

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Extension\TranslationAddType:
        tags:
            - { name: form.type_extension, extended_type: Ibexa\AdminUi\Form\Type\Content\Translation\TranslationAddType }

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Extension\ContentEditType:
        tags:
            - { name: form.type_extension, extended_type: Ibexa\ContentForms\Form\Type\Content\ContentEditType }

    EzSystems\EzPlatformAutomatedTranslationBundle\Form\Extension\LanguageCreateType:
        bind:
            $localeList: '%ibexa.locale.conversion_map%'
        tags:
            - { name: form.type_extension, extended_type: Ibexa\AdminUi\Form\Type\Language\LanguageCreateType }


    EzSystems\EzPlatformAutomatedTranslationBundle\Handler\AutoTranslationActionsHandler:
        lazy: true
        arguments:
            $connection: '@ibexa.persistence.connection'
            $criteriaConverter: '@ibexa.search.legacy.gateway.criteria_converter.location'
