services:
    EzSystems\EzPlatformAutomatedTranslationBundle\Controller\TranslationController:
        decorates: Ibexa\Bundle\AdminUi\Controller\TranslationController
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']